.gitignore
Makefile
cmd/version.go
release/changelog.go
release/changelog_test.go
release/release.go
release/release_test.go
release/version.go
scripts/release.sh
scripts/tag_release.sh

Some tweaks to the final release process, should trigger the release.

Release v0.0.1

---

Makefile
changelog.md
config/storage/storage.go
core/hoard.go
core/storage/filesystem.go
core/storage/logging_store.go
core/storage/memory.go
core/storage/storage.go
core/storage/storage_test.go
core/storage/sync_store.go
release/release.go
server/server.go

Fix panic in SHA256 by not sharing non-goroutine-safe hasher

---

Dockerfile
Makefile
changelog.md
release/release.go

Update docker alpine and go versions

---

changelog.md
core/storage/storage.go
release/release.go

Drop sync pool

---

.circleci/config.yml
project/history.go
scripts/tag_release.sh

Signed-off-by: greg <greg.hill@monax.io>

update tagging & add new version release

---

README.md
integration/docker-compose.yml
integration/test_ipfs.sh

ipfs integration test

---

hoard-js/package.json
project/history.go

bump releases + add notes

---

hoard-js/Makefile
hoard-js/examples.js
hoard-js/index.js
hoard-js/openpgp.js
hoard-js/package-lock.json
hoard-js/package.json
hoard-js/protobuf/hoard.proto

cp hoard.proto into hoard-js

---

cmd/hoarctl/encryption.go
cmd/hoarctl/grants.go
cmd/hoarctl/main.go
cmd/hoarctl/store.go
cmd/hoard/main.go
config/logging/logging.go
config/secrets/secrets.go
config/storage/storage.go
docs/design/examples.md
docs/design/grants.md
grant/grant_test.go
grant/openpgp.go
grant/openpgp_test.go

fixup config, secrets and add granting example

---

CHANGELOG.md
NOTES.md
hoard-js/examples.js
hoard-js/test/grants.js
project/history.go

Prepare for Hoard 3.0.0 release

---

CHANGELOG.md
NOTES.md
project/history.go
server/server.go

Useful for using server in testing scenarios

Provide server Wait() and ListenAddress()

---

.circleci/config.yml
CHANGELOG.md
Makefile
NOTES.md
project/history.go
scripts/release.sh

Fix release process to that binaries are pushed

---

CHANGELOG.md
NOTES.md

update docs for v4

---

package-lock.json
package.json

Signed-off-by: Casey Kuhlman <casey@monax.io>

upgrade js libs we use and publish 1.6.0 so we can leverage v4 endpoints

---

.circleci/Dockerfile

Add goreleaser back to CI image

---

package-lock.json
package.json

upgrade npm deps

---

package-lock.json
package.json

Update lodash to fix CVE-2019-10744

---

api/api.pb.go
cmd/hoarctl/encryption.go
cmd/hoarctl/grants.go
cmd/hoarctl/main.go
cmd/hoarctl/store.go
cmd/hoard/main.go
config/storage.go
grpc_service.go
hoard-js/examples.js
hoard-js/index.js
hoard.go
project/history.go
protobuf/api.proto
server/server.go

stream all large files

---

CHANGELOG.md
NOTES.md
cmd/hoard/config.go
config/secrets.go
config/secrets_test.go
go.mod
go.sum
grant/grant.go
grant/grant_test.go
grant/symmetric.go
grant/symmetric_test.go
package-lock.json
project/history.go
service_test.go

increment hoard version in grant to preserve backwards compatability

---

stores/cloud/cloud.go
stores/ipfs/ipfs.go
stores/memory.go
stores/storage.go

cas should stat before write

---

Dockerfile

remove e shorthand from dockerfile

---

.github/workflows/master.yaml
.github/workflows/test.yaml
Dockerfile
Makefile
README.md

upgrade to go 1.13 in CI and add code cov + other badges

---

.github/workflows/release.yaml
README.md

fix hoard master test badge

---

README.md

fix link in README to LICENSE

---

service_test.go

add service test for downloading embedded metadata

---

hoard_test.go

fix test for new nonce setup

---

CHANGELOG.md
NOTES.md
project/history.go
service.go
service_test.go
streaming.go

chunk get if stored data is > chunk size

---

CHANGELOG.md
NOTES.md
hoard-js/src/examples.ts
hoard-js/src/index.ts
project/history.go

add method to stop reading stream once header received

---

.github/workflows/release.yaml
.github/workflows/test.yaml
.gitignore
Makefile
helm/hoard/.helmignore
helm/hoard/Chart.yaml
helm/hoard/OWNERS
helm/hoard/README.md
helm/hoard/templates/NOTES.txt
helm/hoard/templates/_helpers.tpl
helm/hoard/templates/configmap.yaml
helm/hoard/templates/controller/crd.yaml
helm/hoard/templates/controller/deployment.yaml
helm/hoard/templates/controller/rbac.yaml
helm/hoard/templates/deployment.yaml
helm/hoard/templates/ingress.yaml
helm/hoard/templates/pvc.yaml
helm/hoard/templates/service.yaml
helm/hoard/values.yaml

Add Helm charts

---

.github/Dockerfile
.github/workflows/master.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
Dockerfile
Makefile
scripts/integration/test_gcp.sh
stores/cloud/cloud_test.go

Also:
- runs integration tests on PRs
- upgrades our actions 
- upgrades go
- upgrades Dockerfiles

fix integration tests

---

.github/workflows/release.yaml
.goreleaser.yml
js/package.json
js/src/openpgp.ts

Build on release pushes

---

Makefile
js/package.json
js/src/grants.test.ts
js/src/index.ts
js/src/pipeline.ts
js/src/slice.ts
js/src/stream.ts
js/src/streaming.test.ts
js/src/streaming.ts
js/tsconfig.json
js/yarn.lock
protobuf/reference.proto
scripts/with_hoard.sh
service.go
service_test.go
streaming_service.go

Hoard V9 fixes and tweaks

---

.github/workflows/release.yaml

Push version tag and latest tag on release
